[theme]
primaryColor = "#8b5cf6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f3ff"
textColor = "#262626"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
